repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Find the latest version here: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format
